### ISSUE TITLE
WET site no help text in design guide forms

### ISSUE THREAD

**Issue by firowind** [wet-boew/wet-boew-styleguide#249]
Help text in table of content links to nothing
http://wet-boew.github.io/wet-boew-styleguide/v4/design/forms-en.html#forms-help-text

**Comment by RobJohnston** [comment]
I've noticed that too.  There's a bit of a discussion going on in https://github.com/wet-boew/wet-boew/issues/6613 about how to do it.

**Comment by RobJohnston** [comment]
Since the style guide was updated, the "Help text" section was removed, so this issue can be closed, no?

But I'd still REALLY love to see a best practice for this!  The [issue about how to do it](https://github.com/wet-boew/wet-boew/issues/6613) remains open (I'm leaning towards the modal design).

**Comment by cfarquharson** [comment]
@RobJohnston agreed it would be great to have but I don't want to be the one to make the call as to what solution to use for help.  I don't recall it ever being in the guide (which is probably why the issue was raised in the first place saying that it was in the Table of contents, but not in the content area).

**Comment by RobJohnston** [comment]
But the original issue can be closed, as there is no longer an anchor link that points to nothing.
